#Copyright © 2018 Acumen Solutions, Inc. The Thorax Salesforce Metadata Utility was
#created by Acumen Solutions. Except for the limited rights to use and make copies
#of the Software as provided in a License Agreement, all rights are reserved.

FOLDER_TO_METADATA = {
	"actionLinkGroupTemplates" : ("ActionLinkGroupTemplate", False),
	"analyticSnapshots" : ("AnalyticSnapshot", False),
	"appMenus" : ("AppMenu", False),
	"applications" : ("CustomApplication", False),
	"approvalProcesses" : ("ApprovalProcess", False),
	"assignmentRules" : ("AssignmentRules", False),
	"aura" : ("AuraDefinitionBundle", False),
	"authproviders" : ("AuthProvider", False),
	"autoResponseRules" : ("AutoResponseRules", False),
	"brandingSets" : ("BrandingSet", False),
	"cachePartitions" : ("PlatformCachePartition", False),
	"callCenters" : ("CallCenter", False),
	"campaignInfluenceModels" : ("CampaignInfluenceModel", False),
	"CaseSubjectParticles" : ("CaseSubjectParticle", False),
	"certs" : ("Certificate", False),
	"channelLayouts" : ("ChannelLayout", False),
	"ChatterExtensions" : ("ChatterExtension", False),
	"classes" : ("ApexClass", False),
	"cleanDataServices" : ("CleanDataService", False),
	"communities" : ("Community", False),
	"communityTemplateDefinitions" : ("CommunityTemplateDefinition", False),
	"communityThemeDefinitions" : ("CommunityThemeDefinition", False),
	"components" : ("ApexComponent", False),
	"connectedApps" : ("ConnectedApp", False),
	"contentassets" : ("ContentAsset", False),
	"corsWhitelistOrigins" : ("CorsWhitelistOrigin", False),
	"cspTrustedSites" : ("CspTrustedSite", False),
	"customApplicationComponents" : ("CustomApplicationComponent", False),
	"customMetadata" : ("CustomMetadata", False),
	"customPermissions" : ("CustomPermission", False),
	"dashboards" : ("Dashboard", False),
	"dataSources" : ("ExternalDataSource", False),
	"datacategorygroups" : ("DataCategoryGroup", False),
	"delegateGroups" : ("DelegateGroup", False),
	"documents" : ("Document", False),
	"duplicateRules" : ("DuplicateRule", False),
	"eclair" : ("EclairGeoData", False),
	"email" : ("EmailTemplate", False),
	"emailservices" : ("EmailServicesFunction", False),
	"EmbeddedServiceBranding" : ("EmbeddedServiceBranding", False),
	"EmbeddedServiceConfig" : ("EmbeddedServiceConfig", False),
	"EmbeddedServiceLiveAgent" : ("EmbeddedServiceLiveAgent", False),
	"entitlementProcesses" : ("EntitlementProcess", False),
	"entitlementTemplates" : ("EntitlementTemplate", False),
	"escalationRules" : ("EscalationRules", False),
	"eventDeliveries" : ("EventDelivery", False),
	"eventSubscriptions" : ("EventSubscription", False),
	"externalServiceRegistrations" : ("ExternalServiceRegistration", False),
	"featureParameters" : ("FeatureParameters", False),
	"featureParameterBoolean" : ("FeatureParameterBoolean", False),
	"featureParameterDate" : ("FeatureParameterDate", False),
	"featureParameterInteger" : ("FeatureParameterInteger", False),
	"feedFilters" : ("CustomFeedFilter", False),
	"flexipages" : ("FlexiPage", False),
	"flowCategories" : ("FlowCategory", False),
	"flowDefinitions" : ("FlowDefinition", False),
	"flows" : ("Flow", False),
	"globalValueSetTranslations" : ("GlobalValueSetTranslation", False),
	"globalValueSets" : ("GlobalValueSet", False),
	"groups" : ("Group", False),
	"homePageComponents" : ("HomePageComponent", False),
	"homePageLayouts" : ("HomePageLayout", False),
	"installedPackages" : ("InstalledPackage", False),
	"keywords" : ("KeywordList", False),
	"labels" : ("CustomLabels", False),
	"layouts" : ("Layout", False),
	"LeadConvertSettings" : ("LeadConvertSettings", False),
	"letterhead" : ("Letterhead", False),
	"lightningBolts" : ("LightningBolt", False),
	"lightningExperienceThemes" : ("LightningExperienceTheme", False),
	"lightningcomponents" : ("LightningComponentBundle", False),
	"liveChatAgentConfigs" : ("LiveChatAgentConfig", False),
	"liveChatButtons" : ("LiveChatButton", False),
	"liveChatDeployments" : ("LiveChatDeployment", False),
	"liveChatSensitiveDataRule" : ("LiveChatSensitiveDataRule", False),
	"managedTopics" : ("ManagedTopics", False),
	"matchingRules" : ("MatchingRules", False),
	"milestoneTypes" : ("MilestoneType", False),
	"moderation" : ("ModerationRule", False),
	"namedCredentials" : ("NamedCredential", False),
	"networkBranding" : ("NetworkBranding", False),
	"networks" : ("Network", False),
	"objectTranslations" : ("CustomObjectTranslation", False),
	"objects" : ("CustomObject", False),
	"pages" : ("ApexPage", False),
	"pathAssistants" : ("PathAssistant", False),
	"permissionsets" : ("PermissionSet", False),
	"portals" : ("Portal", False),
	"postTemplates" : ("PostTemplate", False),
	"profilePasswordPolicies" : ("ProfilePasswordPolicy", False),
	"profileSessionSettings" : ("ProfileSessionSetting", False),
	"profiles" : ("Profile", False),
	"queues" : ("Queue", False),
	"quickActions" : ("QuickAction", False),
	"remoteSiteSettings" : ("RemoteSiteSetting", False),
	"reportTypes" : ("ReportType", False),
	"reports" : ("Report", False),
	"roles" : ("Role", False),
	"rule" : ("ModerationRule", False),
	"samlssoconfigs" : ("SamlSsoConfig", False),
	"scontrols" : ("Scontrol", False),
	"settings" : ("Settings", False),
	"sharingRules" : ("SharingRules", False),
	"sharingSets" : ("SharingSet", False),
	"siteDotComSites" : ("SiteDotCom", False),
	"sites" : ("CustomSite", False),
	"skills" : ("Skill", False),
	"standardValueSetTranslations" : ("StandardValueSetTranslation", False),
	"standardValueSets" : ("StandardValueSet", False),
	"staticresources" : ("StaticResource", False),
	"synonymDictionaries" : ("SynonymDictionary", False),
	"tabs" : ("CustomTab", False),
	"territories" : ("Territory", False),
	"territory" : ("Territory", False),
	"territory2" : ("Territory2", False),
	"territory2Models" : ("Territory2Model", False),
	"territory2Rule" : ("Territory2Rule", False),
	"territory2Types" : ("Territory2Type", False),
	"testSuites" : ("ApexTestSuite", False),
	"topicsForObjects" : ("TopicsForObjects", False),
	"transactionSecurityPolicies" : ("TransactionSecurityPolicy", False),
	"translations" : ("Translations", False),
	"triggers" : ("ApexTrigger", False),
	"userCriteria" : ("UserCriteria", False),
	"wapp" : ("WaveApplication", False),
	"wave" : ("WaveApplication", False),
	"wdash" : ("WaveDashboard", False),
	"wdf" : ("WaveDataflow", False),
	"wds" : ("WaveDataset", False),
	"wlens" : ("WaveLens", False),
	"weblinks" : ("CustomPageWebLink", False),
	"workflows" : ("Workflow", False),
	"xmd" : ("WaveXmd", False)
}

OLD_SHARED_FOLDERS = ['featureParameters', 'moderation', 'territories', 'wave']

NEW_SHARED_FOLDERS = [['featureParameters', 'featureParameterBoolean'],
                  ['featureParameters', 'featureParameterDate'],
		  ['featureParameters', 'featureParameterInteger'],
		  ['moderation', 'keywords'],
		  ['moderation', 'rule'],
		  ['territories', 'territory'],
		  ['territories', 'territory2'],
		  ['wave', 'wapp'],
		  ['wave', 'wdash'],
		  ['wave', 'wdf'],
		  ['wave', 'wds'],
		  ['wave', 'wlens'],
		  ['wave', 'xmd']]

TEMP_FOLDERS = ['featureParameterBoolean',
                'featureParameterDate',
		'featureParameterInteger',
		'keywords',
		'rule',
		'territory',
		'territory2',
		'territory2Rule',
		'wapp',
		'wdash',
		'wdf',
		'wds',
		'wlens',
		'xmd']

PACKAGE_FILES = ['package.xml',
                 'destructiveChanges.xml',
                 'destructiveChangesPre.xml',
                 'destructiveChangesPost.xml']

FOLDER_COMPONENTS = ['aura',
                     'territory2Models',
                     'waveTemplates']
